name: 'Mesg-Foundation PR Action'
description: 'Reviews PR'
inputs:
  repo-token:
    description: "a github token for API access"
    required: true
outputs:
  log:
    description: 'The output'
runs:
  using: 'node12'
  main: 'index.js'
